package com.bookworm.bookworm_backend.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a Book entity in the database.
 * This class maps directly to a 'books' table in the MySQL database.
 * We use Lombok annotations for boilerplate code, making the class clean and readable.
 */
@Data // Lombok annotation to automatically generate getters, setters, toString(), etc.
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor.
@AllArgsConstructor // Lombok annotation to generate an all-arguments constructor.
@Entity // Specifies that this class is an entity and maps to a database table.
@Table(name = "books") // Defines the name of the table in the database.
public class Book {

    /**
     * The unique ID of the book. This is the primary key.
     * @Id marks this field as the primary key.
     * @GeneratedValue configures the primary key to be automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the book.
     */
    private String title;

    /**
     * The author of the book.
     */
    private String author;

    /**
     * The year the book was published.
     */
    private Integer publicationYear;

    /**
     * A brief description or summary of the book.
     */
    private String description;

}
